package com.aries.user.gaea.thrift;

import com.aries.user.gaea.model.dto.CompanyRegisterDTO;
import com.aries.user.gaea.model.dto.CompanyResponse;

/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.12.0)", date = "2019-04-25")
public class CompanyBaseService {

  public interface Iface {

    public CompanyResponse companyRegister(CompanyRegisterDTO companyRegisterDTO) throws org.apache.thrift.TException;

    public CompanyResponse getRegisterNO(CompanyRegisterDTO companyRegisterDTO) throws org.apache.thrift.TException;

  }

  public interface AsyncIface {

    public void companyRegister(CompanyRegisterDTO companyRegisterDTO, org.apache.thrift.async.AsyncMethodCallback<CompanyResponse> resultHandler) throws org.apache.thrift.TException;

    public void getRegisterNO(CompanyRegisterDTO companyRegisterDTO, org.apache.thrift.async.AsyncMethodCallback<CompanyResponse> resultHandler) throws org.apache.thrift.TException;

  }

  public static class Client extends org.apache.thrift.TServiceClient implements Iface {
    public static class Factory implements org.apache.thrift.TServiceClientFactory<Client> {
      public Factory() {}
      public Client getClient(org.apache.thrift.protocol.TProtocol prot) {
        return new Client(prot);
      }
      public Client getClient(org.apache.thrift.protocol.TProtocol iprot, org.apache.thrift.protocol.TProtocol oprot) {
        return new Client(iprot, oprot);
      }
    }

    public Client(org.apache.thrift.protocol.TProtocol prot)
    {
      super(prot, prot);
    }

    public Client(org.apache.thrift.protocol.TProtocol iprot, org.apache.thrift.protocol.TProtocol oprot) {
      super(iprot, oprot);
    }

    public CompanyResponse companyRegister(CompanyRegisterDTO companyRegisterDTO) throws org.apache.thrift.TException
    {
      send_companyRegister(companyRegisterDTO);
      return recv_companyRegister();
    }

    public void send_companyRegister(CompanyRegisterDTO companyRegisterDTO) throws org.apache.thrift.TException
    {
      companyRegister_args args = new companyRegister_args();
      args.setCompanyRegisterDTO(companyRegisterDTO);
      sendBase("companyRegister", args);
    }

    public CompanyResponse recv_companyRegister() throws org.apache.thrift.TException
    {
      companyRegister_result result = new companyRegister_result();
      receiveBase(result, "companyRegister");
      if (result.isSetSuccess()) {
        return result.success;
      }
      throw new org.apache.thrift.TApplicationException(org.apache.thrift.TApplicationException.MISSING_RESULT, "companyRegister failed: unknown result");
    }

    public CompanyResponse getRegisterNO(CompanyRegisterDTO companyRegisterDTO) throws org.apache.thrift.TException
    {
      send_getRegisterNO(companyRegisterDTO);
      return recv_getRegisterNO();
    }

    public void send_getRegisterNO(CompanyRegisterDTO companyRegisterDTO) throws org.apache.thrift.TException
    {
      getRegisterNO_args args = new getRegisterNO_args();
      args.setCompanyRegisterDTO(companyRegisterDTO);
      sendBase("getRegisterNO", args);
    }

    public CompanyResponse recv_getRegisterNO() throws org.apache.thrift.TException
    {
      getRegisterNO_result result = new getRegisterNO_result();
      receiveBase(result, "getRegisterNO");
      if (result.isSetSuccess()) {
        return result.success;
      }
      throw new org.apache.thrift.TApplicationException(org.apache.thrift.TApplicationException.MISSING_RESULT, "getRegisterNO failed: unknown result");
    }

  }
  public static class AsyncClient extends org.apache.thrift.async.TAsyncClient implements AsyncIface {
    public static class Factory implements org.apache.thrift.async.TAsyncClientFactory<AsyncClient> {
      private org.apache.thrift.async.TAsyncClientManager clientManager;
      private org.apache.thrift.protocol.TProtocolFactory protocolFactory;
      public Factory(org.apache.thrift.async.TAsyncClientManager clientManager, org.apache.thrift.protocol.TProtocolFactory protocolFactory) {
        this.clientManager = clientManager;
        this.protocolFactory = protocolFactory;
      }
      public AsyncClient getAsyncClient(org.apache.thrift.transport.TNonblockingTransport transport) {
        return new AsyncClient(protocolFactory, clientManager, transport);
      }
    }

    public AsyncClient(org.apache.thrift.protocol.TProtocolFactory protocolFactory, org.apache.thrift.async.TAsyncClientManager clientManager, org.apache.thrift.transport.TNonblockingTransport transport) {
      super(protocolFactory, clientManager, transport);
    }

    public void companyRegister(CompanyRegisterDTO companyRegisterDTO, org.apache.thrift.async.AsyncMethodCallback<CompanyResponse> resultHandler) throws org.apache.thrift.TException {
      checkReady();
      companyRegister_call method_call = new companyRegister_call(companyRegisterDTO, resultHandler, this, ___protocolFactory, ___transport);
      this.___currentMethod = method_call;
      ___manager.call(method_call);
    }

    public static class companyRegister_call extends org.apache.thrift.async.TAsyncMethodCall<CompanyResponse> {
      private CompanyRegisterDTO companyRegisterDTO;
      public companyRegister_call(CompanyRegisterDTO companyRegisterDTO, org.apache.thrift.async.AsyncMethodCallback<CompanyResponse> resultHandler, org.apache.thrift.async.TAsyncClient client, org.apache.thrift.protocol.TProtocolFactory protocolFactory, org.apache.thrift.transport.TNonblockingTransport transport) throws org.apache.thrift.TException {
        super(client, protocolFactory, transport, resultHandler, false);
        this.companyRegisterDTO = companyRegisterDTO;
      }

      public void write_args(org.apache.thrift.protocol.TProtocol prot) throws org.apache.thrift.TException {
        prot.writeMessageBegin(new org.apache.thrift.protocol.TMessage("companyRegister", org.apache.thrift.protocol.TMessageType.CALL, 0));
        companyRegister_args args = new companyRegister_args();
        args.setCompanyRegisterDTO(companyRegisterDTO);
        args.write(prot);
        prot.writeMessageEnd();
      }

      public CompanyResponse getResult() throws org.apache.thrift.TException {
        if (getState() != State.RESPONSE_READ) {
          throw new IllegalStateException("Method call not finished!");
        }
        org.apache.thrift.transport.TMemoryInputTransport memoryTransport = new org.apache.thrift.transport.TMemoryInputTransport(getFrameBuffer().array());
        org.apache.thrift.protocol.TProtocol prot = client.getProtocolFactory().getProtocol(memoryTransport);
        return (new Client(prot)).recv_companyRegister();
      }
    }

    public void getRegisterNO(CompanyRegisterDTO companyRegisterDTO, org.apache.thrift.async.AsyncMethodCallback<CompanyResponse> resultHandler) throws org.apache.thrift.TException {
      checkReady();
      getRegisterNO_call method_call = new getRegisterNO_call(companyRegisterDTO, resultHandler, this, ___protocolFactory, ___transport);
      this.___currentMethod = method_call;
      ___manager.call(method_call);
    }

    public static class getRegisterNO_call extends org.apache.thrift.async.TAsyncMethodCall<CompanyResponse> {
      private CompanyRegisterDTO companyRegisterDTO;
      public getRegisterNO_call(CompanyRegisterDTO companyRegisterDTO, org.apache.thrift.async.AsyncMethodCallback<CompanyResponse> resultHandler, org.apache.thrift.async.TAsyncClient client, org.apache.thrift.protocol.TProtocolFactory protocolFactory, org.apache.thrift.transport.TNonblockingTransport transport) throws org.apache.thrift.TException {
        super(client, protocolFactory, transport, resultHandler, false);
        this.companyRegisterDTO = companyRegisterDTO;
      }

      public void write_args(org.apache.thrift.protocol.TProtocol prot) throws org.apache.thrift.TException {
        prot.writeMessageBegin(new org.apache.thrift.protocol.TMessage("getRegisterNO", org.apache.thrift.protocol.TMessageType.CALL, 0));
        getRegisterNO_args args = new getRegisterNO_args();
        args.setCompanyRegisterDTO(companyRegisterDTO);
        args.write(prot);
        prot.writeMessageEnd();
      }

      public CompanyResponse getResult() throws org.apache.thrift.TException {
        if (getState() != State.RESPONSE_READ) {
          throw new IllegalStateException("Method call not finished!");
        }
        org.apache.thrift.transport.TMemoryInputTransport memoryTransport = new org.apache.thrift.transport.TMemoryInputTransport(getFrameBuffer().array());
        org.apache.thrift.protocol.TProtocol prot = client.getProtocolFactory().getProtocol(memoryTransport);
        return (new Client(prot)).recv_getRegisterNO();
      }
    }

  }

  public static class Processor<I extends Iface> extends org.apache.thrift.TBaseProcessor<I> implements org.apache.thrift.TProcessor {
    private static final org.slf4j.Logger _LOGGER = org.slf4j.LoggerFactory.getLogger(Processor.class.getName());
    public Processor(I iface) {
      super(iface, getProcessMap(new java.util.HashMap<String, org.apache.thrift.ProcessFunction<I, ? extends org.apache.thrift.TBase>>()));
    }

    protected Processor(I iface, java.util.Map<String, org.apache.thrift.ProcessFunction<I, ? extends org.apache.thrift.TBase>> processMap) {
      super(iface, getProcessMap(processMap));
    }

    private static <I extends Iface> java.util.Map<String,  org.apache.thrift.ProcessFunction<I, ? extends org.apache.thrift.TBase>> getProcessMap(java.util.Map<String, org.apache.thrift.ProcessFunction<I, ? extends  org.apache.thrift.TBase>> processMap) {
      processMap.put("companyRegister", new companyRegister());
      processMap.put("getRegisterNO", new getRegisterNO());
      return processMap;
    }

    public static class companyRegister<I extends Iface> extends org.apache.thrift.ProcessFunction<I, companyRegister_args> {
      public companyRegister() {
        super("companyRegister");
      }

      public companyRegister_args getEmptyArgsInstance() {
        return new companyRegister_args();
      }

      protected boolean isOneway() {
        return false;
      }

      @Override
      protected boolean rethrowUnhandledExceptions() {
        return false;
      }

      public companyRegister_result getResult(I iface, companyRegister_args args) throws org.apache.thrift.TException {
        companyRegister_result result = new companyRegister_result();
        result.success = iface.companyRegister(args.companyRegisterDTO);
        return result;
      }
    }

    public static class getRegisterNO<I extends Iface> extends org.apache.thrift.ProcessFunction<I, getRegisterNO_args> {
      public getRegisterNO() {
        super("getRegisterNO");
      }

      public getRegisterNO_args getEmptyArgsInstance() {
        return new getRegisterNO_args();
      }

      protected boolean isOneway() {
        return false;
      }

      @Override
      protected boolean rethrowUnhandledExceptions() {
        return false;
      }

      public getRegisterNO_result getResult(I iface, getRegisterNO_args args) throws org.apache.thrift.TException {
        getRegisterNO_result result = new getRegisterNO_result();
        result.success = iface.getRegisterNO(args.companyRegisterDTO);
        return result;
      }
    }

  }

  public static class AsyncProcessor<I extends AsyncIface> extends org.apache.thrift.TBaseAsyncProcessor<I> {
    private static final org.slf4j.Logger _LOGGER = org.slf4j.LoggerFactory.getLogger(AsyncProcessor.class.getName());
    public AsyncProcessor(I iface) {
      super(iface, getProcessMap(new java.util.HashMap<String, org.apache.thrift.AsyncProcessFunction<I, ? extends org.apache.thrift.TBase, ?>>()));
    }

    protected AsyncProcessor(I iface, java.util.Map<String,  org.apache.thrift.AsyncProcessFunction<I, ? extends  org.apache.thrift.TBase, ?>> processMap) {
      super(iface, getProcessMap(processMap));
    }

    private static <I extends AsyncIface> java.util.Map<String,  org.apache.thrift.AsyncProcessFunction<I, ? extends  org.apache.thrift.TBase,?>> getProcessMap(java.util.Map<String,  org.apache.thrift.AsyncProcessFunction<I, ? extends  org.apache.thrift.TBase, ?>> processMap) {
      processMap.put("companyRegister", new companyRegister());
      processMap.put("getRegisterNO", new getRegisterNO());
      return processMap;
    }

    public static class companyRegister<I extends AsyncIface> extends org.apache.thrift.AsyncProcessFunction<I, companyRegister_args, CompanyResponse> {
      public companyRegister() {
        super("companyRegister");
      }

      public companyRegister_args getEmptyArgsInstance() {
        return new companyRegister_args();
      }

      public org.apache.thrift.async.AsyncMethodCallback<CompanyResponse> getResultHandler(final org.apache.thrift.server.AbstractNonblockingServer.AsyncFrameBuffer fb, final int seqid) {
        final org.apache.thrift.AsyncProcessFunction fcall = this;
        return new org.apache.thrift.async.AsyncMethodCallback<CompanyResponse>() { 
          public void onComplete(CompanyResponse o) {
            companyRegister_result result = new companyRegister_result();
            result.success = o;
            try {
              fcall.sendResponse(fb, result, org.apache.thrift.protocol.TMessageType.REPLY,seqid);
            } catch (org.apache.thrift.transport.TTransportException e) {
              _LOGGER.error("TTransportException writing to internal frame buffer", e);
              fb.close();
            } catch (Exception e) {
              _LOGGER.error("Exception writing to internal frame buffer", e);
              onError(e);
            }
          }
          public void onError(Exception e) {
            byte msgType = org.apache.thrift.protocol.TMessageType.REPLY;
            org.apache.thrift.TSerializable msg;
            companyRegister_result result = new companyRegister_result();
            if (e instanceof org.apache.thrift.transport.TTransportException) {
              _LOGGER.error("TTransportException inside handler", e);
              fb.close();
              return;
            } else if (e instanceof org.apache.thrift.TApplicationException) {
              _LOGGER.error("TApplicationException inside handler", e);
              msgType = org.apache.thrift.protocol.TMessageType.EXCEPTION;
              msg = (org.apache.thrift.TApplicationException)e;
            } else {
              _LOGGER.error("Exception inside handler", e);
              msgType = org.apache.thrift.protocol.TMessageType.EXCEPTION;
              msg = new org.apache.thrift.TApplicationException(org.apache.thrift.TApplicationException.INTERNAL_ERROR, e.getMessage());
            }
            try {
              fcall.sendResponse(fb,msg,msgType,seqid);
            } catch (Exception ex) {
              _LOGGER.error("Exception writing to internal frame buffer", ex);
              fb.close();
            }
          }
        };
      }

      protected boolean isOneway() {
        return false;
      }

      public void start(I iface, companyRegister_args args, org.apache.thrift.async.AsyncMethodCallback<CompanyResponse> resultHandler) throws org.apache.thrift.TException {
        iface.companyRegister(args.companyRegisterDTO,resultHandler);
      }
    }

    public static class getRegisterNO<I extends AsyncIface> extends org.apache.thrift.AsyncProcessFunction<I, getRegisterNO_args, CompanyResponse> {
      public getRegisterNO() {
        super("getRegisterNO");
      }

      public getRegisterNO_args getEmptyArgsInstance() {
        return new getRegisterNO_args();
      }

      public org.apache.thrift.async.AsyncMethodCallback<CompanyResponse> getResultHandler(final org.apache.thrift.server.AbstractNonblockingServer.AsyncFrameBuffer fb, final int seqid) {
        final org.apache.thrift.AsyncProcessFunction fcall = this;
        return new org.apache.thrift.async.AsyncMethodCallback<CompanyResponse>() { 
          public void onComplete(CompanyResponse o) {
            getRegisterNO_result result = new getRegisterNO_result();
            result.success = o;
            try {
              fcall.sendResponse(fb, result, org.apache.thrift.protocol.TMessageType.REPLY,seqid);
            } catch (org.apache.thrift.transport.TTransportException e) {
              _LOGGER.error("TTransportException writing to internal frame buffer", e);
              fb.close();
            } catch (Exception e) {
              _LOGGER.error("Exception writing to internal frame buffer", e);
              onError(e);
            }
          }
          public void onError(Exception e) {
            byte msgType = org.apache.thrift.protocol.TMessageType.REPLY;
            org.apache.thrift.TSerializable msg;
            getRegisterNO_result result = new getRegisterNO_result();
            if (e instanceof org.apache.thrift.transport.TTransportException) {
              _LOGGER.error("TTransportException inside handler", e);
              fb.close();
              return;
            } else if (e instanceof org.apache.thrift.TApplicationException) {
              _LOGGER.error("TApplicationException inside handler", e);
              msgType = org.apache.thrift.protocol.TMessageType.EXCEPTION;
              msg = (org.apache.thrift.TApplicationException)e;
            } else {
              _LOGGER.error("Exception inside handler", e);
              msgType = org.apache.thrift.protocol.TMessageType.EXCEPTION;
              msg = new org.apache.thrift.TApplicationException(org.apache.thrift.TApplicationException.INTERNAL_ERROR, e.getMessage());
            }
            try {
              fcall.sendResponse(fb,msg,msgType,seqid);
            } catch (Exception ex) {
              _LOGGER.error("Exception writing to internal frame buffer", ex);
              fb.close();
            }
          }
        };
      }

      protected boolean isOneway() {
        return false;
      }

      public void start(I iface, getRegisterNO_args args, org.apache.thrift.async.AsyncMethodCallback<CompanyResponse> resultHandler) throws org.apache.thrift.TException {
        iface.getRegisterNO(args.companyRegisterDTO,resultHandler);
      }
    }

  }

  public static class companyRegister_args implements org.apache.thrift.TBase<companyRegister_args, companyRegister_args._Fields>, java.io.Serializable, Cloneable, Comparable<companyRegister_args>   {
    private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("companyRegister_args");

    private static final org.apache.thrift.protocol.TField COMPANY_REGISTER_DTO_FIELD_DESC = new org.apache.thrift.protocol.TField("companyRegisterDTO", org.apache.thrift.protocol.TType.STRUCT, (short)1);

    private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new companyRegister_argsStandardSchemeFactory();
    private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new companyRegister_argsTupleSchemeFactory();

    public @org.apache.thrift.annotation.Nullable CompanyRegisterDTO companyRegisterDTO; // required

    /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
    public enum _Fields implements org.apache.thrift.TFieldIdEnum {
      COMPANY_REGISTER_DTO((short)1, "companyRegisterDTO");

      private static final java.util.Map<String, _Fields> byName = new java.util.HashMap<String, _Fields>();

      static {
        for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
          byName.put(field.getFieldName(), field);
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, or null if its not found.
       */
      @org.apache.thrift.annotation.Nullable
      public static _Fields findByThriftId(int fieldId) {
        switch(fieldId) {
          case 1: // COMPANY_REGISTER_DTO
            return COMPANY_REGISTER_DTO;
          default:
            return null;
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, throwing an exception
       * if it is not found.
       */
      public static _Fields findByThriftIdOrThrow(int fieldId) {
        _Fields fields = findByThriftId(fieldId);
        if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
        return fields;
      }

      /**
       * Find the _Fields constant that matches name, or null if its not found.
       */
      @org.apache.thrift.annotation.Nullable
      public static _Fields findByName(String name) {
        return byName.get(name);
      }

      private final short _thriftId;
      private final String _fieldName;

      _Fields(short thriftId, String fieldName) {
        _thriftId = thriftId;
        _fieldName = fieldName;
      }

      public short getThriftFieldId() {
        return _thriftId;
      }

      public String getFieldName() {
        return _fieldName;
      }
    }

    // isset id assignments
    public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
    static {
      java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
      tmpMap.put(_Fields.COMPANY_REGISTER_DTO, new org.apache.thrift.meta_data.FieldMetaData("companyRegisterDTO", org.apache.thrift.TFieldRequirementType.DEFAULT, 
          new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, CompanyRegisterDTO.class)));
      metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
      org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(companyRegister_args.class, metaDataMap);
    }

    public companyRegister_args() {
    }

    public companyRegister_args(
      CompanyRegisterDTO companyRegisterDTO)
    {
      this();
      this.companyRegisterDTO = companyRegisterDTO;
    }

    /**
     * Performs a deep copy on <i>other</i>.
     */
    public companyRegister_args(companyRegister_args other) {
      if (other.isSetCompanyRegisterDTO()) {
        this.companyRegisterDTO = new CompanyRegisterDTO(other.companyRegisterDTO);
      }
    }

    public companyRegister_args deepCopy() {
      return new companyRegister_args(this);
    }

    @Override
    public void clear() {
      this.companyRegisterDTO = null;
    }

    @org.apache.thrift.annotation.Nullable
    public CompanyRegisterDTO getCompanyRegisterDTO() {
      return this.companyRegisterDTO;
    }

    public companyRegister_args setCompanyRegisterDTO(@org.apache.thrift.annotation.Nullable CompanyRegisterDTO companyRegisterDTO) {
      this.companyRegisterDTO = companyRegisterDTO;
      return this;
    }

    public void unsetCompanyRegisterDTO() {
      this.companyRegisterDTO = null;
    }

    /** Returns true if field companyRegisterDTO is set (has been assigned a value) and false otherwise */
    public boolean isSetCompanyRegisterDTO() {
      return this.companyRegisterDTO != null;
    }

    public void setCompanyRegisterDTOIsSet(boolean value) {
      if (!value) {
        this.companyRegisterDTO = null;
      }
    }

    public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable Object value) {
      switch (field) {
      case COMPANY_REGISTER_DTO:
        if (value == null) {
          unsetCompanyRegisterDTO();
        } else {
          setCompanyRegisterDTO((CompanyRegisterDTO)value);
        }
        break;

      }
    }

    @org.apache.thrift.annotation.Nullable
    public Object getFieldValue(_Fields field) {
      switch (field) {
      case COMPANY_REGISTER_DTO:
        return getCompanyRegisterDTO();

      }
      throw new IllegalStateException();
    }

    /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
    public boolean isSet(_Fields field) {
      if (field == null) {
        throw new IllegalArgumentException();
      }

      switch (field) {
      case COMPANY_REGISTER_DTO:
        return isSetCompanyRegisterDTO();
      }
      throw new IllegalStateException();
    }

    @Override
    public boolean equals(Object that) {
      if (that == null)
        return false;
      if (that instanceof companyRegister_args)
        return this.equals((companyRegister_args)that);
      return false;
    }

    public boolean equals(companyRegister_args that) {
      if (that == null)
        return false;
      if (this == that)
        return true;

      boolean this_present_companyRegisterDTO = true && this.isSetCompanyRegisterDTO();
      boolean that_present_companyRegisterDTO = true && that.isSetCompanyRegisterDTO();
      if (this_present_companyRegisterDTO || that_present_companyRegisterDTO) {
        if (!(this_present_companyRegisterDTO && that_present_companyRegisterDTO))
          return false;
        if (!this.companyRegisterDTO.equals(that.companyRegisterDTO))
          return false;
      }

      return true;
    }

    @Override
    public int hashCode() {
      int hashCode = 1;

      hashCode = hashCode * 8191 + ((isSetCompanyRegisterDTO()) ? 131071 : 524287);
      if (isSetCompanyRegisterDTO())
        hashCode = hashCode * 8191 + companyRegisterDTO.hashCode();

      return hashCode;
    }

    @Override
    public int compareTo(companyRegister_args other) {
      if (!getClass().equals(other.getClass())) {
        return getClass().getName().compareTo(other.getClass().getName());
      }

      int lastComparison = 0;

      lastComparison = Boolean.valueOf(isSetCompanyRegisterDTO()).compareTo(other.isSetCompanyRegisterDTO());
      if (lastComparison != 0) {
        return lastComparison;
      }
      if (isSetCompanyRegisterDTO()) {
        lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.companyRegisterDTO, other.companyRegisterDTO);
        if (lastComparison != 0) {
          return lastComparison;
        }
      }
      return 0;
    }

    @org.apache.thrift.annotation.Nullable
    public _Fields fieldForId(int fieldId) {
      return _Fields.findByThriftId(fieldId);
    }

    public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
      scheme(iprot).read(iprot, this);
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
      scheme(oprot).write(oprot, this);
    }

    @Override
    public String toString() {
      StringBuilder sb = new StringBuilder("companyRegister_args(");
      boolean first = true;

      sb.append("companyRegisterDTO:");
      if (this.companyRegisterDTO == null) {
        sb.append("null");
      } else {
        sb.append(this.companyRegisterDTO);
      }
      first = false;
      sb.append(")");
      return sb.toString();
    }

    public void validate() throws org.apache.thrift.TException {
      // check for required fields
      // check for sub-struct validity
      if (companyRegisterDTO != null) {
        companyRegisterDTO.validate();
      }
    }

    private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
      try {
        write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
      try {
        read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private static class companyRegister_argsStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
      public companyRegister_argsStandardScheme getScheme() {
        return new companyRegister_argsStandardScheme();
      }
    }

    private static class companyRegister_argsStandardScheme extends org.apache.thrift.scheme.StandardScheme<companyRegister_args> {

      public void read(org.apache.thrift.protocol.TProtocol iprot, companyRegister_args struct) throws org.apache.thrift.TException {
        org.apache.thrift.protocol.TField schemeField;
        iprot.readStructBegin();
        while (true)
        {
          schemeField = iprot.readFieldBegin();
          if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
            break;
          }
          switch (schemeField.id) {
            case 1: // COMPANY_REGISTER_DTO
              if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
                struct.companyRegisterDTO = new CompanyRegisterDTO();
                struct.companyRegisterDTO.read(iprot);
                struct.setCompanyRegisterDTOIsSet(true);
              } else { 
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            default:
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
          }
          iprot.readFieldEnd();
        }
        iprot.readStructEnd();

        // check for required fields of primitive type, which can't be checked in the validate method
        struct.validate();
      }

      public void write(org.apache.thrift.protocol.TProtocol oprot, companyRegister_args struct) throws org.apache.thrift.TException {
        struct.validate();

        oprot.writeStructBegin(STRUCT_DESC);
        if (struct.companyRegisterDTO != null) {
          oprot.writeFieldBegin(COMPANY_REGISTER_DTO_FIELD_DESC);
          struct.companyRegisterDTO.write(oprot);
          oprot.writeFieldEnd();
        }
        oprot.writeFieldStop();
        oprot.writeStructEnd();
      }

    }

    private static class companyRegister_argsTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
      public companyRegister_argsTupleScheme getScheme() {
        return new companyRegister_argsTupleScheme();
      }
    }

    private static class companyRegister_argsTupleScheme extends org.apache.thrift.scheme.TupleScheme<companyRegister_args> {

      @Override
      public void write(org.apache.thrift.protocol.TProtocol prot, companyRegister_args struct) throws org.apache.thrift.TException {
        org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
        java.util.BitSet optionals = new java.util.BitSet();
        if (struct.isSetCompanyRegisterDTO()) {
          optionals.set(0);
        }
        oprot.writeBitSet(optionals, 1);
        if (struct.isSetCompanyRegisterDTO()) {
          struct.companyRegisterDTO.write(oprot);
        }
      }

      @Override
      public void read(org.apache.thrift.protocol.TProtocol prot, companyRegister_args struct) throws org.apache.thrift.TException {
        org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
        java.util.BitSet incoming = iprot.readBitSet(1);
        if (incoming.get(0)) {
          struct.companyRegisterDTO = new CompanyRegisterDTO();
          struct.companyRegisterDTO.read(iprot);
          struct.setCompanyRegisterDTOIsSet(true);
        }
      }
    }

    private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
      return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
    }
  }

  public static class companyRegister_result implements org.apache.thrift.TBase<companyRegister_result, companyRegister_result._Fields>, java.io.Serializable, Cloneable, Comparable<companyRegister_result>   {
    private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("companyRegister_result");

    private static final org.apache.thrift.protocol.TField SUCCESS_FIELD_DESC = new org.apache.thrift.protocol.TField("success", org.apache.thrift.protocol.TType.STRUCT, (short)0);

    private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new companyRegister_resultStandardSchemeFactory();
    private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new companyRegister_resultTupleSchemeFactory();

    public @org.apache.thrift.annotation.Nullable CompanyResponse success; // required

    /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
    public enum _Fields implements org.apache.thrift.TFieldIdEnum {
      SUCCESS((short)0, "success");

      private static final java.util.Map<String, _Fields> byName = new java.util.HashMap<String, _Fields>();

      static {
        for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
          byName.put(field.getFieldName(), field);
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, or null if its not found.
       */
      @org.apache.thrift.annotation.Nullable
      public static _Fields findByThriftId(int fieldId) {
        switch(fieldId) {
          case 0: // SUCCESS
            return SUCCESS;
          default:
            return null;
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, throwing an exception
       * if it is not found.
       */
      public static _Fields findByThriftIdOrThrow(int fieldId) {
        _Fields fields = findByThriftId(fieldId);
        if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
        return fields;
      }

      /**
       * Find the _Fields constant that matches name, or null if its not found.
       */
      @org.apache.thrift.annotation.Nullable
      public static _Fields findByName(String name) {
        return byName.get(name);
      }

      private final short _thriftId;
      private final String _fieldName;

      _Fields(short thriftId, String fieldName) {
        _thriftId = thriftId;
        _fieldName = fieldName;
      }

      public short getThriftFieldId() {
        return _thriftId;
      }

      public String getFieldName() {
        return _fieldName;
      }
    }

    // isset id assignments
    public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
    static {
      java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
      tmpMap.put(_Fields.SUCCESS, new org.apache.thrift.meta_data.FieldMetaData("success", org.apache.thrift.TFieldRequirementType.DEFAULT, 
          new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, CompanyResponse.class)));
      metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
      org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(companyRegister_result.class, metaDataMap);
    }

    public companyRegister_result() {
    }

    public companyRegister_result(
      CompanyResponse success)
    {
      this();
      this.success = success;
    }

    /**
     * Performs a deep copy on <i>other</i>.
     */
    public companyRegister_result(companyRegister_result other) {
      if (other.isSetSuccess()) {
        this.success = new CompanyResponse(other.success);
      }
    }

    public companyRegister_result deepCopy() {
      return new companyRegister_result(this);
    }

    @Override
    public void clear() {
      this.success = null;
    }

    @org.apache.thrift.annotation.Nullable
    public CompanyResponse getSuccess() {
      return this.success;
    }

    public companyRegister_result setSuccess(@org.apache.thrift.annotation.Nullable CompanyResponse success) {
      this.success = success;
      return this;
    }

    public void unsetSuccess() {
      this.success = null;
    }

    /** Returns true if field success is set (has been assigned a value) and false otherwise */
    public boolean isSetSuccess() {
      return this.success != null;
    }

    public void setSuccessIsSet(boolean value) {
      if (!value) {
        this.success = null;
      }
    }

    public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable Object value) {
      switch (field) {
      case SUCCESS:
        if (value == null) {
          unsetSuccess();
        } else {
          setSuccess((CompanyResponse)value);
        }
        break;

      }
    }

    @org.apache.thrift.annotation.Nullable
    public Object getFieldValue(_Fields field) {
      switch (field) {
      case SUCCESS:
        return getSuccess();

      }
      throw new IllegalStateException();
    }

    /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
    public boolean isSet(_Fields field) {
      if (field == null) {
        throw new IllegalArgumentException();
      }

      switch (field) {
      case SUCCESS:
        return isSetSuccess();
      }
      throw new IllegalStateException();
    }

    @Override
    public boolean equals(Object that) {
      if (that == null)
        return false;
      if (that instanceof companyRegister_result)
        return this.equals((companyRegister_result)that);
      return false;
    }

    public boolean equals(companyRegister_result that) {
      if (that == null)
        return false;
      if (this == that)
        return true;

      boolean this_present_success = true && this.isSetSuccess();
      boolean that_present_success = true && that.isSetSuccess();
      if (this_present_success || that_present_success) {
        if (!(this_present_success && that_present_success))
          return false;
        if (!this.success.equals(that.success))
          return false;
      }

      return true;
    }

    @Override
    public int hashCode() {
      int hashCode = 1;

      hashCode = hashCode * 8191 + ((isSetSuccess()) ? 131071 : 524287);
      if (isSetSuccess())
        hashCode = hashCode * 8191 + success.hashCode();

      return hashCode;
    }

    @Override
    public int compareTo(companyRegister_result other) {
      if (!getClass().equals(other.getClass())) {
        return getClass().getName().compareTo(other.getClass().getName());
      }

      int lastComparison = 0;

      lastComparison = Boolean.valueOf(isSetSuccess()).compareTo(other.isSetSuccess());
      if (lastComparison != 0) {
        return lastComparison;
      }
      if (isSetSuccess()) {
        lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.success, other.success);
        if (lastComparison != 0) {
          return lastComparison;
        }
      }
      return 0;
    }

    @org.apache.thrift.annotation.Nullable
    public _Fields fieldForId(int fieldId) {
      return _Fields.findByThriftId(fieldId);
    }

    public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
      scheme(iprot).read(iprot, this);
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
      scheme(oprot).write(oprot, this);
      }

    @Override
    public String toString() {
      StringBuilder sb = new StringBuilder("companyRegister_result(");
      boolean first = true;

      sb.append("success:");
      if (this.success == null) {
        sb.append("null");
      } else {
        sb.append(this.success);
      }
      first = false;
      sb.append(")");
      return sb.toString();
    }

    public void validate() throws org.apache.thrift.TException {
      // check for required fields
      // check for sub-struct validity
      if (success != null) {
        success.validate();
      }
    }

    private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
      try {
        write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
      try {
        read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private static class companyRegister_resultStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
      public companyRegister_resultStandardScheme getScheme() {
        return new companyRegister_resultStandardScheme();
      }
    }

    private static class companyRegister_resultStandardScheme extends org.apache.thrift.scheme.StandardScheme<companyRegister_result> {

      public void read(org.apache.thrift.protocol.TProtocol iprot, companyRegister_result struct) throws org.apache.thrift.TException {
        org.apache.thrift.protocol.TField schemeField;
        iprot.readStructBegin();
        while (true)
        {
          schemeField = iprot.readFieldBegin();
          if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
            break;
          }
          switch (schemeField.id) {
            case 0: // SUCCESS
              if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
                struct.success = new CompanyResponse();
                struct.success.read(iprot);
                struct.setSuccessIsSet(true);
              } else { 
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            default:
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
          }
          iprot.readFieldEnd();
        }
        iprot.readStructEnd();

        // check for required fields of primitive type, which can't be checked in the validate method
        struct.validate();
      }

      public void write(org.apache.thrift.protocol.TProtocol oprot, companyRegister_result struct) throws org.apache.thrift.TException {
        struct.validate();

        oprot.writeStructBegin(STRUCT_DESC);
        if (struct.success != null) {
          oprot.writeFieldBegin(SUCCESS_FIELD_DESC);
          struct.success.write(oprot);
          oprot.writeFieldEnd();
        }
        oprot.writeFieldStop();
        oprot.writeStructEnd();
      }

    }

    private static class companyRegister_resultTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
      public companyRegister_resultTupleScheme getScheme() {
        return new companyRegister_resultTupleScheme();
      }
    }

    private static class companyRegister_resultTupleScheme extends org.apache.thrift.scheme.TupleScheme<companyRegister_result> {

      @Override
      public void write(org.apache.thrift.protocol.TProtocol prot, companyRegister_result struct) throws org.apache.thrift.TException {
        org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
        java.util.BitSet optionals = new java.util.BitSet();
        if (struct.isSetSuccess()) {
          optionals.set(0);
        }
        oprot.writeBitSet(optionals, 1);
        if (struct.isSetSuccess()) {
          struct.success.write(oprot);
        }
      }

      @Override
      public void read(org.apache.thrift.protocol.TProtocol prot, companyRegister_result struct) throws org.apache.thrift.TException {
        org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
        java.util.BitSet incoming = iprot.readBitSet(1);
        if (incoming.get(0)) {
          struct.success = new CompanyResponse();
          struct.success.read(iprot);
          struct.setSuccessIsSet(true);
        }
      }
    }

    private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
      return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
    }
  }

  public static class getRegisterNO_args implements org.apache.thrift.TBase<getRegisterNO_args, getRegisterNO_args._Fields>, java.io.Serializable, Cloneable, Comparable<getRegisterNO_args>   {
    private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("getRegisterNO_args");

    private static final org.apache.thrift.protocol.TField COMPANY_REGISTER_DTO_FIELD_DESC = new org.apache.thrift.protocol.TField("companyRegisterDTO", org.apache.thrift.protocol.TType.STRUCT, (short)1);

    private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new getRegisterNO_argsStandardSchemeFactory();
    private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new getRegisterNO_argsTupleSchemeFactory();

    public @org.apache.thrift.annotation.Nullable CompanyRegisterDTO companyRegisterDTO; // required

    /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
    public enum _Fields implements org.apache.thrift.TFieldIdEnum {
      COMPANY_REGISTER_DTO((short)1, "companyRegisterDTO");

      private static final java.util.Map<String, _Fields> byName = new java.util.HashMap<String, _Fields>();

      static {
        for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
          byName.put(field.getFieldName(), field);
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, or null if its not found.
       */
      @org.apache.thrift.annotation.Nullable
      public static _Fields findByThriftId(int fieldId) {
        switch(fieldId) {
          case 1: // COMPANY_REGISTER_DTO
            return COMPANY_REGISTER_DTO;
          default:
            return null;
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, throwing an exception
       * if it is not found.
       */
      public static _Fields findByThriftIdOrThrow(int fieldId) {
        _Fields fields = findByThriftId(fieldId);
        if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
        return fields;
      }

      /**
       * Find the _Fields constant that matches name, or null if its not found.
       */
      @org.apache.thrift.annotation.Nullable
      public static _Fields findByName(String name) {
        return byName.get(name);
      }

      private final short _thriftId;
      private final String _fieldName;

      _Fields(short thriftId, String fieldName) {
        _thriftId = thriftId;
        _fieldName = fieldName;
      }

      public short getThriftFieldId() {
        return _thriftId;
      }

      public String getFieldName() {
        return _fieldName;
      }
    }

    // isset id assignments
    public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
    static {
      java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
      tmpMap.put(_Fields.COMPANY_REGISTER_DTO, new org.apache.thrift.meta_data.FieldMetaData("companyRegisterDTO", org.apache.thrift.TFieldRequirementType.DEFAULT, 
          new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, CompanyRegisterDTO.class)));
      metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
      org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(getRegisterNO_args.class, metaDataMap);
    }

    public getRegisterNO_args() {
    }

    public getRegisterNO_args(
      CompanyRegisterDTO companyRegisterDTO)
    {
      this();
      this.companyRegisterDTO = companyRegisterDTO;
    }

    /**
     * Performs a deep copy on <i>other</i>.
     */
    public getRegisterNO_args(getRegisterNO_args other) {
      if (other.isSetCompanyRegisterDTO()) {
        this.companyRegisterDTO = new CompanyRegisterDTO(other.companyRegisterDTO);
      }
    }

    public getRegisterNO_args deepCopy() {
      return new getRegisterNO_args(this);
    }

    @Override
    public void clear() {
      this.companyRegisterDTO = null;
    }

    @org.apache.thrift.annotation.Nullable
    public CompanyRegisterDTO getCompanyRegisterDTO() {
      return this.companyRegisterDTO;
    }

    public getRegisterNO_args setCompanyRegisterDTO(@org.apache.thrift.annotation.Nullable CompanyRegisterDTO companyRegisterDTO) {
      this.companyRegisterDTO = companyRegisterDTO;
      return this;
    }

    public void unsetCompanyRegisterDTO() {
      this.companyRegisterDTO = null;
    }

    /** Returns true if field companyRegisterDTO is set (has been assigned a value) and false otherwise */
    public boolean isSetCompanyRegisterDTO() {
      return this.companyRegisterDTO != null;
    }

    public void setCompanyRegisterDTOIsSet(boolean value) {
      if (!value) {
        this.companyRegisterDTO = null;
      }
    }

    public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable Object value) {
      switch (field) {
      case COMPANY_REGISTER_DTO:
        if (value == null) {
          unsetCompanyRegisterDTO();
        } else {
          setCompanyRegisterDTO((CompanyRegisterDTO)value);
        }
        break;

      }
    }

    @org.apache.thrift.annotation.Nullable
    public Object getFieldValue(_Fields field) {
      switch (field) {
      case COMPANY_REGISTER_DTO:
        return getCompanyRegisterDTO();

      }
      throw new IllegalStateException();
    }

    /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
    public boolean isSet(_Fields field) {
      if (field == null) {
        throw new IllegalArgumentException();
      }

      switch (field) {
      case COMPANY_REGISTER_DTO:
        return isSetCompanyRegisterDTO();
      }
      throw new IllegalStateException();
    }

    @Override
    public boolean equals(Object that) {
      if (that == null)
        return false;
      if (that instanceof getRegisterNO_args)
        return this.equals((getRegisterNO_args)that);
      return false;
    }

    public boolean equals(getRegisterNO_args that) {
      if (that == null)
        return false;
      if (this == that)
        return true;

      boolean this_present_companyRegisterDTO = true && this.isSetCompanyRegisterDTO();
      boolean that_present_companyRegisterDTO = true && that.isSetCompanyRegisterDTO();
      if (this_present_companyRegisterDTO || that_present_companyRegisterDTO) {
        if (!(this_present_companyRegisterDTO && that_present_companyRegisterDTO))
          return false;
        if (!this.companyRegisterDTO.equals(that.companyRegisterDTO))
          return false;
      }

      return true;
    }

    @Override
    public int hashCode() {
      int hashCode = 1;

      hashCode = hashCode * 8191 + ((isSetCompanyRegisterDTO()) ? 131071 : 524287);
      if (isSetCompanyRegisterDTO())
        hashCode = hashCode * 8191 + companyRegisterDTO.hashCode();

      return hashCode;
    }

    @Override
    public int compareTo(getRegisterNO_args other) {
      if (!getClass().equals(other.getClass())) {
        return getClass().getName().compareTo(other.getClass().getName());
      }

      int lastComparison = 0;

      lastComparison = Boolean.valueOf(isSetCompanyRegisterDTO()).compareTo(other.isSetCompanyRegisterDTO());
      if (lastComparison != 0) {
        return lastComparison;
      }
      if (isSetCompanyRegisterDTO()) {
        lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.companyRegisterDTO, other.companyRegisterDTO);
        if (lastComparison != 0) {
          return lastComparison;
        }
      }
      return 0;
    }

    @org.apache.thrift.annotation.Nullable
    public _Fields fieldForId(int fieldId) {
      return _Fields.findByThriftId(fieldId);
    }

    public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
      scheme(iprot).read(iprot, this);
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
      scheme(oprot).write(oprot, this);
    }

    @Override
    public String toString() {
      StringBuilder sb = new StringBuilder("getRegisterNO_args(");
      boolean first = true;

      sb.append("companyRegisterDTO:");
      if (this.companyRegisterDTO == null) {
        sb.append("null");
      } else {
        sb.append(this.companyRegisterDTO);
      }
      first = false;
      sb.append(")");
      return sb.toString();
    }

    public void validate() throws org.apache.thrift.TException {
      // check for required fields
      // check for sub-struct validity
      if (companyRegisterDTO != null) {
        companyRegisterDTO.validate();
      }
    }

    private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
      try {
        write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
      try {
        read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private static class getRegisterNO_argsStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
      public getRegisterNO_argsStandardScheme getScheme() {
        return new getRegisterNO_argsStandardScheme();
      }
    }

    private static class getRegisterNO_argsStandardScheme extends org.apache.thrift.scheme.StandardScheme<getRegisterNO_args> {

      public void read(org.apache.thrift.protocol.TProtocol iprot, getRegisterNO_args struct) throws org.apache.thrift.TException {
        org.apache.thrift.protocol.TField schemeField;
        iprot.readStructBegin();
        while (true)
        {
          schemeField = iprot.readFieldBegin();
          if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
            break;
          }
          switch (schemeField.id) {
            case 1: // COMPANY_REGISTER_DTO
              if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
                struct.companyRegisterDTO = new CompanyRegisterDTO();
                struct.companyRegisterDTO.read(iprot);
                struct.setCompanyRegisterDTOIsSet(true);
              } else { 
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            default:
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
          }
          iprot.readFieldEnd();
        }
        iprot.readStructEnd();

        // check for required fields of primitive type, which can't be checked in the validate method
        struct.validate();
      }

      public void write(org.apache.thrift.protocol.TProtocol oprot, getRegisterNO_args struct) throws org.apache.thrift.TException {
        struct.validate();

        oprot.writeStructBegin(STRUCT_DESC);
        if (struct.companyRegisterDTO != null) {
          oprot.writeFieldBegin(COMPANY_REGISTER_DTO_FIELD_DESC);
          struct.companyRegisterDTO.write(oprot);
          oprot.writeFieldEnd();
        }
        oprot.writeFieldStop();
        oprot.writeStructEnd();
      }

    }

    private static class getRegisterNO_argsTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
      public getRegisterNO_argsTupleScheme getScheme() {
        return new getRegisterNO_argsTupleScheme();
      }
    }

    private static class getRegisterNO_argsTupleScheme extends org.apache.thrift.scheme.TupleScheme<getRegisterNO_args> {

      @Override
      public void write(org.apache.thrift.protocol.TProtocol prot, getRegisterNO_args struct) throws org.apache.thrift.TException {
        org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
        java.util.BitSet optionals = new java.util.BitSet();
        if (struct.isSetCompanyRegisterDTO()) {
          optionals.set(0);
        }
        oprot.writeBitSet(optionals, 1);
        if (struct.isSetCompanyRegisterDTO()) {
          struct.companyRegisterDTO.write(oprot);
        }
      }

      @Override
      public void read(org.apache.thrift.protocol.TProtocol prot, getRegisterNO_args struct) throws org.apache.thrift.TException {
        org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
        java.util.BitSet incoming = iprot.readBitSet(1);
        if (incoming.get(0)) {
          struct.companyRegisterDTO = new CompanyRegisterDTO();
          struct.companyRegisterDTO.read(iprot);
          struct.setCompanyRegisterDTOIsSet(true);
        }
      }
    }

    private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
      return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
    }
  }

  public static class getRegisterNO_result implements org.apache.thrift.TBase<getRegisterNO_result, getRegisterNO_result._Fields>, java.io.Serializable, Cloneable, Comparable<getRegisterNO_result>   {
    private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("getRegisterNO_result");

    private static final org.apache.thrift.protocol.TField SUCCESS_FIELD_DESC = new org.apache.thrift.protocol.TField("success", org.apache.thrift.protocol.TType.STRUCT, (short)0);

    private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new getRegisterNO_resultStandardSchemeFactory();
    private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new getRegisterNO_resultTupleSchemeFactory();

    public @org.apache.thrift.annotation.Nullable CompanyResponse success; // required

    /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
    public enum _Fields implements org.apache.thrift.TFieldIdEnum {
      SUCCESS((short)0, "success");

      private static final java.util.Map<String, _Fields> byName = new java.util.HashMap<String, _Fields>();

      static {
        for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
          byName.put(field.getFieldName(), field);
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, or null if its not found.
       */
      @org.apache.thrift.annotation.Nullable
      public static _Fields findByThriftId(int fieldId) {
        switch(fieldId) {
          case 0: // SUCCESS
            return SUCCESS;
          default:
            return null;
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, throwing an exception
       * if it is not found.
       */
      public static _Fields findByThriftIdOrThrow(int fieldId) {
        _Fields fields = findByThriftId(fieldId);
        if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
        return fields;
      }

      /**
       * Find the _Fields constant that matches name, or null if its not found.
       */
      @org.apache.thrift.annotation.Nullable
      public static _Fields findByName(String name) {
        return byName.get(name);
      }

      private final short _thriftId;
      private final String _fieldName;

      _Fields(short thriftId, String fieldName) {
        _thriftId = thriftId;
        _fieldName = fieldName;
      }

      public short getThriftFieldId() {
        return _thriftId;
      }

      public String getFieldName() {
        return _fieldName;
      }
    }

    // isset id assignments
    public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
    static {
      java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
      tmpMap.put(_Fields.SUCCESS, new org.apache.thrift.meta_data.FieldMetaData("success", org.apache.thrift.TFieldRequirementType.DEFAULT, 
          new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, CompanyResponse.class)));
      metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
      org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(getRegisterNO_result.class, metaDataMap);
    }

    public getRegisterNO_result() {
    }

    public getRegisterNO_result(
      CompanyResponse success)
    {
      this();
      this.success = success;
    }

    /**
     * Performs a deep copy on <i>other</i>.
     */
    public getRegisterNO_result(getRegisterNO_result other) {
      if (other.isSetSuccess()) {
        this.success = new CompanyResponse(other.success);
      }
    }

    public getRegisterNO_result deepCopy() {
      return new getRegisterNO_result(this);
    }

    @Override
    public void clear() {
      this.success = null;
    }

    @org.apache.thrift.annotation.Nullable
    public CompanyResponse getSuccess() {
      return this.success;
    }

    public getRegisterNO_result setSuccess(@org.apache.thrift.annotation.Nullable CompanyResponse success) {
      this.success = success;
      return this;
    }

    public void unsetSuccess() {
      this.success = null;
    }

    /** Returns true if field success is set (has been assigned a value) and false otherwise */
    public boolean isSetSuccess() {
      return this.success != null;
    }

    public void setSuccessIsSet(boolean value) {
      if (!value) {
        this.success = null;
      }
    }

    public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable Object value) {
      switch (field) {
      case SUCCESS:
        if (value == null) {
          unsetSuccess();
        } else {
          setSuccess((CompanyResponse)value);
        }
        break;

      }
    }

    @org.apache.thrift.annotation.Nullable
    public Object getFieldValue(_Fields field) {
      switch (field) {
      case SUCCESS:
        return getSuccess();

      }
      throw new IllegalStateException();
    }

    /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
    public boolean isSet(_Fields field) {
      if (field == null) {
        throw new IllegalArgumentException();
      }

      switch (field) {
      case SUCCESS:
        return isSetSuccess();
      }
      throw new IllegalStateException();
    }

    @Override
    public boolean equals(Object that) {
      if (that == null)
        return false;
      if (that instanceof getRegisterNO_result)
        return this.equals((getRegisterNO_result)that);
      return false;
    }

    public boolean equals(getRegisterNO_result that) {
      if (that == null)
        return false;
      if (this == that)
        return true;

      boolean this_present_success = true && this.isSetSuccess();
      boolean that_present_success = true && that.isSetSuccess();
      if (this_present_success || that_present_success) {
        if (!(this_present_success && that_present_success))
          return false;
        if (!this.success.equals(that.success))
          return false;
      }

      return true;
    }

    @Override
    public int hashCode() {
      int hashCode = 1;

      hashCode = hashCode * 8191 + ((isSetSuccess()) ? 131071 : 524287);
      if (isSetSuccess())
        hashCode = hashCode * 8191 + success.hashCode();

      return hashCode;
    }

    @Override
    public int compareTo(getRegisterNO_result other) {
      if (!getClass().equals(other.getClass())) {
        return getClass().getName().compareTo(other.getClass().getName());
      }

      int lastComparison = 0;

      lastComparison = Boolean.valueOf(isSetSuccess()).compareTo(other.isSetSuccess());
      if (lastComparison != 0) {
        return lastComparison;
      }
      if (isSetSuccess()) {
        lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.success, other.success);
        if (lastComparison != 0) {
          return lastComparison;
        }
      }
      return 0;
    }

    @org.apache.thrift.annotation.Nullable
    public _Fields fieldForId(int fieldId) {
      return _Fields.findByThriftId(fieldId);
    }

    public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
      scheme(iprot).read(iprot, this);
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
      scheme(oprot).write(oprot, this);
      }

    @Override
    public String toString() {
      StringBuilder sb = new StringBuilder("getRegisterNO_result(");
      boolean first = true;

      sb.append("success:");
      if (this.success == null) {
        sb.append("null");
      } else {
        sb.append(this.success);
      }
      first = false;
      sb.append(")");
      return sb.toString();
    }

    public void validate() throws org.apache.thrift.TException {
      // check for required fields
      // check for sub-struct validity
      if (success != null) {
        success.validate();
      }
    }

    private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
      try {
        write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
      try {
        read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private static class getRegisterNO_resultStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
      public getRegisterNO_resultStandardScheme getScheme() {
        return new getRegisterNO_resultStandardScheme();
      }
    }

    private static class getRegisterNO_resultStandardScheme extends org.apache.thrift.scheme.StandardScheme<getRegisterNO_result> {

      public void read(org.apache.thrift.protocol.TProtocol iprot, getRegisterNO_result struct) throws org.apache.thrift.TException {
        org.apache.thrift.protocol.TField schemeField;
        iprot.readStructBegin();
        while (true)
        {
          schemeField = iprot.readFieldBegin();
          if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
            break;
          }
          switch (schemeField.id) {
            case 0: // SUCCESS
              if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
                struct.success = new CompanyResponse();
                struct.success.read(iprot);
                struct.setSuccessIsSet(true);
              } else { 
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            default:
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
          }
          iprot.readFieldEnd();
        }
        iprot.readStructEnd();

        // check for required fields of primitive type, which can't be checked in the validate method
        struct.validate();
      }

      public void write(org.apache.thrift.protocol.TProtocol oprot, getRegisterNO_result struct) throws org.apache.thrift.TException {
        struct.validate();

        oprot.writeStructBegin(STRUCT_DESC);
        if (struct.success != null) {
          oprot.writeFieldBegin(SUCCESS_FIELD_DESC);
          struct.success.write(oprot);
          oprot.writeFieldEnd();
        }
        oprot.writeFieldStop();
        oprot.writeStructEnd();
      }

    }

    private static class getRegisterNO_resultTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
      public getRegisterNO_resultTupleScheme getScheme() {
        return new getRegisterNO_resultTupleScheme();
      }
    }

    private static class getRegisterNO_resultTupleScheme extends org.apache.thrift.scheme.TupleScheme<getRegisterNO_result> {

      @Override
      public void write(org.apache.thrift.protocol.TProtocol prot, getRegisterNO_result struct) throws org.apache.thrift.TException {
        org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
        java.util.BitSet optionals = new java.util.BitSet();
        if (struct.isSetSuccess()) {
          optionals.set(0);
        }
        oprot.writeBitSet(optionals, 1);
        if (struct.isSetSuccess()) {
          struct.success.write(oprot);
        }
      }

      @Override
      public void read(org.apache.thrift.protocol.TProtocol prot, getRegisterNO_result struct) throws org.apache.thrift.TException {
        org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
        java.util.BitSet incoming = iprot.readBitSet(1);
        if (incoming.get(0)) {
          struct.success = new CompanyResponse();
          struct.success.read(iprot);
          struct.setSuccessIsSet(true);
        }
      }
    }

    private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
      return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
    }
  }

}
